MercuryTechnologies/buck2-prelude

haskell/tools/generate_target_metadata.py, haskell/tools/generate_toolchain_library_catalog.py
Closes https://github.com/MercuryTechnologies/the-culture-repo/issues/147
This addresses errors of the form
```
Traceback (most recent call last):
File <builtin>, in <module>
* prelude/haskell/compile.bzl:688, in do_compile
for module_name in post_order_traversal(graph):
error: Key `".nix.store.h9vyn35122fb9570y6gh34qndlwmv51d-async-2.2.4.lib.ghc-9.8.2.lib.x86_64-linux-ghc-9.8.2.async-2.2.4-InWOgiTOEySF1536J1W8dc.Control.Concurrent.Async"` was not found
--> prelude/utils/graph_utils.bzl:60:13
|
60 |             rdeps[dep].append(node)
|             ^^^^^^^^^^
```
The problem was that the output format of `ghc-pkg` changed slightly, omitting a terminal `---`, which confused the `ghc-pkg dump` parser.
This PR fixes the parser, and also introduces an additional check to produce a more …
=> Fix 'Key `".nix.store..."` was not found' error

haskell/compile.bzl, haskell/tools/generate_target_metadata.py, haskell/tools/generate_toolchain_library_catalog.py
Closes https://github.com/MercuryTechnologies/the-culture-repo/issues/131
Toolchain library dependencies are now specified on the GHC command-line using `-package-id` flags instead of `-package` flags. This resolves issues where GHC reports module dependencies from hidden package, despite these packages being listed on the command line using `-package` flags.
We also need to use `-package-id` flags when generating the dependency metadata JSON file. Unfortunately, doing this cleanly when we generate the flags in Starlark is not quite as easy as at the build stage. So, this PR instead patches the GHC flags within the Python script that invokes GHC -M. I'd like to find a better way to do this, but will leave this open for a future improvement.
- **Parse package-id field**
- **Track …
=> Fix issues with internal package dependencies

haskell/haskell.bzl
Otherwise this led to a spurious error like this:
```
Local command returned non-zero exit code 1
Reproduce locally: `env -- 'BUCK_SCRATCH_PATH=buck-out/v2/tmp/root/904931f735703749/backend/src/__backend_infra__/haskel ...<omitted>... nfra__/db-static buck-out/v2/gen/root/904931f735703749/backend/src/__backend_infra__/pkg-static.conf (run `buck2 log what-failed` to get the full command)`
stdout:
stderr:
WARNING: cache does not exist: ./package.cache
ghc will fail to read this package db. Use 'ghc-pkg recache' to fix.
ghc-pkg-9.8.2: "the input" (line 14, column 1):
unexpected operator "#"
expecting field or section name
```
=> Do not set `GHC_PACKAGE_PATH` when it is empty

haskell/haskell_ghci.bzl
This is needed when the script is referring to another output that depends on
other artifacts at runtime.
=> Add hidden inputs to final ghci script

haskell/compile.bzl, haskell/haskell.bzl, haskell/library_info.bzl, haskell/tools/ghc_wrapper.py
Expands recompilation avoidance to changes in the transitive package dependency graph that don't impact a given module.
Consider the following targets and assume that we built module `A`.
```
haskell_library(
name = "a",
srcs = ["A.hs"],  # imports B1
deps = [":b"],
)
haskell_library(
name = "b",
srcs = [
"B1.hs",
"B2.hs",
],
)
```
Assume that we change the targets as follows:
```
haskell_library(
name = "a",
srcs = ["A.hs"],  # imports B1
deps = [":b"],
)
haskell_library(
name = "b",
srcs = [
"B1.hs",
"B2.hs",  # imports C
],
deps = [":c"],
)
haskell_library(
name = "c",
srcs = ["C.hs"],
)
```
If we now issue a build of module `A` again then `A` should ideally not be recompiled but instead fetched from cache, because it does not transitively depend on the newly added package dependency …
=> Recompilation avoidance on -package-db arguments

haskell/compile.bzl, haskell/haskell.bzl, haskell/library_info.bzl, haskell/toolchain.bzl, haskell/tools/generate_toolchain_library_catalog.py
This changes the handling of package db's for haskell targets by using a tset to maintain a dependency tree for nix haskell packages.
For a haskell module, `-package-db` flags are passed for each of the required haskell toolchain libraries including their dependent package dbs.
This way only the the minimally required haskell nix packages are build by buck2 that are needed for a specific haskell target.
- Cleanup _common_compile_args
- Add `packages` field to `HaskellToolchainInfo`
- Add `HaskellPackagesInfo` record
- Use package db from toolchain packages info
- Add `HaskellPackagesInfoTSet` and a dynamic provider
- Add `dynamic` field to `HaskellPackagesInfo`
- Add package dependencies to HaskellLibraryInfo
- Add `packages` reduction for HaskellLibraryInfoTSet
- Add `package_db` …
=> Use individual package DBs for nix haskell libs

haskell/compile.bzl
`_compile_module_args` was only used once and did no longer properly encapsulate the generation of compiler args for module compilation.
Inlining the function revealed several opportunities to remove duplicate code.
A possible next step is to factor out arguments that are shared across all modules and generate them outside of the loop over modules.
- **Inline _compile_module_args**
- **Remove duplicate compile_cmd object**
- **Inline compile_args_for_file**
- **Remove indirection for srcs**
- **Remove CompileArgsInfo**
- **Remove intermediate CompileResultInfo**
- **Remove unused field type variant**
- **inline packages_info.exposed_package_modules**
- **Remove redundant branch**
- **TODO note**
- **Remove redundant intermediate variable**
- **remove inline markers**
- **remove redundant …
=> Inline _compile_module_args

decls/haskell_common.bzl, haskell/compile.bzl, haskell/haskell.bzl, haskell/toolchain.bzl, haskell/tools/generate_target_metadata.py, haskell/tools/ghc_wrapper.py
- Remove duplicate variable
- Remove superfluous `-package-db` flags passed to ghc
- Keep track of the path for each haskell package db
- Add `--nix-pkg` argument to `ghc_wrapper.py` and `generate_target_metadata.py`
- Pass `--nix-pkg` flag for each direct toolchain library dependency
- Allow to declare dependencies for haskell sources manually
=> Add binaries from haskell packages to PATH

haskell/compile.bzl
Inlines the parts of `get_packages_info` relevant to module compilation and removes them from `get_packages_info`.
The two cases shared relatively little common code and separating them and inlining the module case into `_compile_module` uncovered a few opportunities for deduplication.
- **inline get_packages_info for _compile_module**
- **Inline bool constants**
- **Resolve branches under bool constants**
- **Remove redundant if**
- **Remove duplicate variables**
- **Inline pkg_name**
- **Inline packages_info.packagedb_args**
- **Remove unused exposed_package_libs**
- **inline exposed_package_modules**
- **inline exposed_package_dbs**
- **Remove unused PackagesInfo**
- **get_packages_info remove unused package_deps**
- **get_packages_info consistently use no empty lib**
- **Revert …
=> Split per-module and per-package packages info

haskell/compile.bzl
Factor out the analysis and generation of arguments that are shared across all modules in a package.
- **Pass only the current module to _compile_module**
- **bubble up non module specific args**
- **bubble cpp flags**
- **bubble up non-module specific extra source files**
- **Factor out common command line arguments**
- **Move common compile flags**
- **Factor out direct_deps_info**
- **Factor out direct_deps_by_name**
- **pull down per module analysis**
- **Factor out packagedb tagging**
- **Factor out common package-db flags**
- **remove unused arguments**
=> Factor out flags shared across modules

haskell/compile.bzl, haskell/toolchain.bzl
- **Avoid recompilation for binaries from haskell packages**
- **Remove `path` projection for HaskellPackageDbTSet**
=> Avoid recompilation with haskell binaries

haskell/tools/generate_target_metadata.py, haskell/tools/generate_toolchain_library_catalog.py
- **TMP: capture raw GHC -M output**
- **The -opt-json GHC flag was removed**
- **update TH detection**
- **calculate module mapping**
- **determine module graph**
- **determine package and toolchain dependencies**
- **resolve package-ids of package dependencies**
- **obtain base package id from catalog**
- **Remove unused code**
=> Update to latest GHC -M JSON output

haskell/compile.bzl
Sets `-fprefer-byte-code` for TH splices instead of passing dependency module object files on the command-line.
Assumes [GHC patches][ghc-patches] to enable bytecode linking for one-shot mode for the home module and package dependencies.
[ghc-patches]: https://gitlab.haskell.org/torsten.schmits/ghc/-/commits/tcr/ghc982-2024-07-11-a
- **remove objects from TH compile actions**
- **Set -fprefer-byte-code for TH splices**
- **Remove .dyn_o to .o symlinks**
- **Remove module package dependency tracking**
- **Remove module toolchain lib dependency tracking**
- **Remove module objects reduction**
=> Enable bytecode linking for TH slices

haskell/compile.bzl, haskell/haskell.bzl, haskell/haskell_haddock.bzl, haskell/tools/generate_target_metadata.py, haskell/util.bzl
Adds support for Haskell targets that contain module dependency cycles and boot files.
Note, the output of GHC -dep-json could be improved to better support this use-case. The current implementation has to make assumptions about the imports of the `.hs-boot` file.
- **Extract boot module dependencies**
- **Generate module objects for boot files**
- **Extend module dep graph by boot deps**
- **Copy package deps onto boot module**
- **Use md_file for `-outputdir`**
- **Skip stubdir output for boot modules**
- **Skip .o-boot files when linking**
- **Simplify boot module dep graph integration**
- **Calculate reverse boot file dep graph**
- **Add boot module dependencies**
- **Revert "try to fix -i(dir)"**
- **Revert "No more md_json dependency per module"**
- **Set ignore_artifacts on md_file …
=> Support hs-boot files

decls/haskell_common.bzl, decls/haskell_rules.bzl, haskell/compile.bzl, haskell/haskell.bzl, haskell/haskell_haddock.bzl, haskell/util.bzl
This PR introduces a `src_strip_prefix` attribute for haskell_library rules. AFAICS, source prefix stripping is not needed for haskell_binary rules, since that attribute is only relevant for package conf files and for locating interface files.
**Note**
We also could infer the source prefix from the md.json file automatically.
But the information is needed at three places currently: 
1) when compiling a module
2) when writing the package conf file(s)
3) when generating haddock docs
The first has access to the md.json file since its actions are run inside a dynamic output action, but the latter ones do not. 
Using the information from the md.json file, it also would be possible to support source files in several sub-directories -- not sure how commonly this is seen in the wild (for cabal …
=> Support source prefix stripping in Buck2

haskell/tools/generate_target_metadata.py, haskell/tools/ghc_wrapper.py
Before, failed `ghc_wrapper` invocations would print a Python stack trace including the entire failed command (typically hundreds of lines long). By just returning a non-zero integer and not producing the requested output, Buck2 will realize the build failed and just print stdout/stderr (and the full command can be retrieved with `buck2 log what-failed`).
---
IMPORTANT: Please don't raise pull requests here, but at
[facebook/buck2](https://github.com/facebook/buck2/pulls).
The [`prelude`](https://github.com/facebook/buck2/tree/main/prelude) directory
is a mirror of this repo, but that repo also features CI tests and is more
actively monitored. Any PR's landing there will automatically show up here at
the same time.
=> Improve error messages for GHC compilation failures

haskell/compile.bzl, haskell/tools/generate_target_metadata.py, haskell/tools/ghc_wrapper.py
This is to work around Buck2 swallowing stdout on successful builds, as discussed in https://github.com/MercuryTechnologies/buck2-prelude/pull/2#issuecomment-2292992546.
- **Improve error messages for GHC compilation failures**
- **Improve error messages for metadata generation**
- **Redirect GHC stdout to stderr**
=> Redirect GHC stdout to stderr

haskell/compile.bzl, haskell/tools/generate_target_metadata.py
- **Filter boot files from GHC -M command line**
- **Handle boot files in module_mapping**
- **Handle boot files in module graph**
- **Handle boot files in package deps**
- **Support imports in boot files**
- **wording**
Adds support for Haskell boot files that themselves import other Haskell modules or other Haskell boot modules.
Depends on https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11994/diffs?commit_id=ecf726ab5a75fdc0a92c0849cce82ed227240360
=> Support boot files with imports

decls/haskell_rules.bzl
See https://github.com/MercuryTechnologies/buck2-prelude/pull/27
=> Fix: Missing instance of external_tools_arg

decls/haskell_common.bzl, decls/haskell_rules.bzl, haskell/compile.bzl, haskell/haskell.bzl, haskell/haskell_haddock.bzl, haskell/util.bzl
- **Determine source prefix automatically**
- **Use inferred source_prefixes in _compile_module**
- **Move package conf actions into dynamic ouput**
- **Infer source prefixes for exposed-modules and import-dirs**
- **Properly handle html output with source prefixes**
- **Fix handling of output directories**
- **Handle source prefix for boot modules**
- ... revert changes using the `src_strip_prefix` attribute
=> Infer source prefix automatically

haskell/compile.bzl, haskell/haskell.bzl, haskell/library_info.bzl
Using multiple source directories results in multiple entries in the `import-dirs` field of the package conf file.
With multiple entries in that field, GHC tries to find all interface files for the exposed modules (see [1] and [2]).
For the dependency analysis we do not want to depend on any interface files. To make this work we have to ensure there only is a single entry. But also, the multiple entries are needed for compilation (using the empty package dbs). That is why yet another package db is introduced here.
[1]: https://gitlab.haskell.org/ghc/ghc/-/blob/3a145315052d6f66f9682ecff87b522011165d59/compiler/GHC/Unit/Finder.hs#L491-499
[2]: https://github.com/tweag/mercury-ghc-internal/issues/51
=> Support multiple source directories

haskell/haskell.bzl
Filter out boot modules when generating the exposed-modules entry in the
package database.
=> Do not expose boot modules
